### ISSUE TITLE
Implementar suporte para Gitpod

### ISSUE THREAD

**Issue by IvoPereira** [devpt-org/site#6]
Adicionar suporte para o Gitpod no projeto permitira uma rápida inicialização do ambiente de desenvolvimento.

Podemos basear a implementação numa já existente, por exemplo [na que fizemos para o bot de Discord](https://github.com/devpt-org/discord-bot/pull/28).

**Comment by HackerinoS2** [comment]
Boas. Vou experimentar implementar suporte com o Gitpod.

**Comment by HackerinoS2** [comment]
Preciso de ajuda.

Acho que estou bastante perto de chegar ao que é necessário para termos o Gitpod a funcionar corretamente mas tenho um problema que ainda não consegui dar a volta.

Neste momento tenho o seguinte: 

```
tasks:
  - name: Setup .env
    init: cp .env.example .env

  - name: Get Laravel Sail dependencies via docker
    init: |
      docker run --rm \-u "$(id -u):$(id -g)" \-v "$(pwd):/app" -w /app \composer:2 \composer install --ignore-platform-reqs
      gp sync-done composer

  - name: Execute Laravel Sail
    init: gp sync-await composer
    command: ./vendor/bin/sail up
  
#Como o "sail up" executado em cima não "para", nunca vou conseguir emitir um evento "gp sync-done"
  - name: Run dev
   #Este bash falha pois ele não espera pelo "sail up"
    before: ./vendor/bin/sail bash
    init: php artisan key:generate && php artisan storage:link
    command: composer install && npm install && npm run dev
```

O meu problema é abrir o sail bash na altura correta para finalizar os restantes comandos.

@IvoPereira Consegues dar-me uma ajudinha?

**Comment by raulcorreia7** [comment]
Acho que o teu problema é questão de lançares um processo em background.
https://linuxhint.com/send-process-background-linux/

Experimenta lançar o  commando como
./vendor/bin/sail up &
e continuar.
Senão funcionar, aconselho a juntares isto num único comando em Run dev.

Exemplo:
 - name: Run dev
   #Este bash falha pois ele não espera pelo "sail up"
    before: ./vendor/bin/sail bash
    init: php artisan key:generate && php artisan storage:link
    command: (./vendor/bin/sail up &) && composer install && npm install && npm run dev

```
tasks:
  - name: Setup .env
    init: cp .env.example .env

  - name: Get Laravel Sail dependencies via docker
    init: |
      docker run --rm \-u "$(id -u):$(id -g)" \-v "$(pwd):/app" -w /app \composer:2 \composer install --ignore-platform-reqs
      gp sync-done composer

  - name: Execute Laravel Sail
    init: gp sync-await composer
    command: ./vendor/bin/sail up & 

 - name: Run dev
   #Este bash falha pois ele não espera pelo "sail up"
    before: ./vendor/bin/sail bash
    init: php artisan key:generate && php artisan storage:link
    command: composer install && npm install && npm run dev
```
